version: 2

project_name: todo

before:
  hooks:
    - go mod tidy

builds:
  - id: todo
    binary: todo
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids:
      - todo
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  filters:
    include:
      - "^- "

release:
  draft: false
