Source "support/vhs/_base.tape"

Hide
Type@1ms "todo add update dependencies +done"
Enter
Type@1ms "todo add publish v0.1 release +release"
Enter
Type@1ms "todo add review pull request +review"
Enter
Type@1ms "clear"
Enter
Show
Sleep 1s

Type "todo list"
Enter
Sleep 1s
Type "todo del 1"
Enter
Sleep 1s
Type "todo del +done"
Enter
Sleep 1s
Type "todo del +bug/+release"
Enter
Sleep 1s
Type "todo ls"
Enter
Sleep 5s
